app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

#app_bundle:
#    resource: "@AppBundle/Controller/MemberController.php"
#    type:     annotation
#    prefix:   /user