security:
    encoders:
        AppBundle\Entity\Login:
            algorithm: bcrypt
            cost: 13

    providers:
        user_login:
            entity:
                class: AppBundle\Entity\Login
                property: username

    firewalls:

        admin_secured_area:
            pattern: /admin
            anonymous: ~
            form_login:
                login_path: /admin/secured/login
                check_path: /admin/secured/login
                default_target_path: /admin
                always_use_default_target_path: true
            logout:
                path:   /admin/secured/logout
                target: /admin/secured/login

        user_secured_area:
            pattern: /user
            anonymous: ~
            form_login:
                login_path: /user/secured/login
                check_path: /user/secured/login
                default_target_path: /user
                always_use_default_target_path: true
            logout:
                path:   /user/secured/logout
                target: /user/secured/login

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin/secured/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/secured/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, roles: ROLE_ADMIN }
        - { path: ^/user/*, roles: ROLE_ADMIN }