security:
    encoders:
        AppBundle\Entity\Login:
            algorithm: bcrypt
            cost: 13

    providers:
        user_login:
            entity:
                class: AppBundle\Entity\Login
                property: username

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: admin
                always_use_default_target_path: true
            logout:
                path:   /login/logout
                target: /login
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
